#!/usr/bin/env ruby

def c( command )
	puts command
	return `#{command}`
end

c( 'hg addremove' )
puts commit_result = c( "hg com -m \"#{ARGV[0] || 'Automatic commit' }\"" )
c( "hg push #{ARGV[2]}" ) if ARGV[1] == 'false' || !commit_result.include?( 'nothing changed' )
